# -*- coding: utf-8 -*-
"""1. Matplotlib Examples.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1649sxqayfpcaXLKgtsXldh3eFtHZJ3pX
"""

import matplotlib.pyplot as plt

# Sample Data
x = [1, 2, 3, 4, 5]
y = [10, 20, 25, 30, 40]

# Line Plot
plt.plot(x, y, marker='o', color='blue', label='Line Plot')
plt.title("Line Plot Example")
plt.xlabel("X-axis")
plt.ylabel("Y-axis")
plt.legend()
plt.show()

# Bar Chart
plt.bar(x, y, color='green')
plt.title("Bar Chart Example")
plt.show()

# Histogram
data = [5, 7, 7, 8, 10, 10, 10, 12, 15]
plt.hist(data, bins=5, color='orange', edgecolor='black')
plt.title("Histogram Example")
plt.show()

# Scatter Plot
plt.scatter(x, y, color='red')
plt.title("Scatter Plot Example")
plt.show()