# -*- coding: utf-8 -*-
"""2. Seaborn Examples.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1649sxqayfpcaXLKgtsXldh3eFtHZJ3pX
"""

import seaborn as sns
import pandas as pd

# Sample DataFrame
data = pd.DataFrame({
    'Age': [25, 30, 35, 40, 22, 28, 33, 38],
    'Salary': [50000, 60000, 65000, 70000, 48000, 58000, 62000, 68000],
    'Department': ['HR', 'IT', 'IT', 'HR', 'Sales', 'Sales', 'IT', 'HR']
})

# Histogram
sns.histplot(data['Age'], bins=5, kde=True)
plt.show()

# Boxplot
sns.boxplot(x='Department', y='Salary', data=data)
plt.show()

# Heatmap (correlation)
corr = data[['Age','Salary']].corr()
sns.heatmap(corr, annot=True, cmap='coolwarm')
plt.show()

# Pairplot
sns.pairplot(data[['Age', 'Salary']])
plt.show()

