# -*- coding: utf-8 -*-
"""Client Project – Dashboard (Relationships).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1649sxqayfpcaXLKgtsXldh3eFtHZJ3pX
"""

# Dashboard: Visualizing relationships between features

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# Sample dataset
data = pd.DataFrame({
    'Experience': [1,2,3,4,5,6,7,8],
    'Salary': [30000, 35000, 40000, 45000, 50000, 55000, 60000, 65000],
    'Department': ['HR','IT','HR','IT','Sales','Sales','IT','HR']
})

# Scatter plot
plt.figure(figsize=(6,4))
sns.scatterplot(x='Experience', y='Salary', hue='Department', data=data, s=100)
plt.title("Experience vs Salary")
plt.show()

# Histogram of salaries
plt.figure(figsize=(6,4))
sns.histplot(data['Salary'], bins=5, kde=True, color='purple')
plt.title("Salary Distribution")
plt.show()

# Boxplot
plt.figure(figsize=(6,4))
sns.boxplot(x='Department', y='Salary', data=data)
plt.title("Salary by Department")
plt.show()