# -*- coding: utf-8 -*-
"""Client Project – Data Cleaning & Aggregation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1649sxqayfpcaXLKgtsXldh3eFtHZJ3pX
"""

import pandas as pd

# Sample dataset
data = {
    'Department': ['HR', 'IT', 'HR', 'IT', 'Sales', 'Sales'],
    'Employee': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank'],
    'Salary': [50000, 60000, None, 65000, 45000, None]
}

df = pd.DataFrame(data)

# Remove missing salaries
df_cleaned = df.dropna()

# Calculate average salary per department
avg_salary = df_cleaned.groupby('Department')['Salary'].mean()
print("Cleaned Data:\n", df_cleaned)
print("Average Salary by Department:\n", avg_salary)

