# -*- coding: utf-8 -*-
"""Numpy Operations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1649sxqayfpcaXLKgtsXldh3eFtHZJ3pX
"""

import numpy as np

# Create arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Element-wise operations
print("Addition:", a + b)
print("Multiplication:", a * b)

# Broadcasting example
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([10, 20, 30])
print("Broadcasted Addition:\n", c + d)

# Useful functions
print("Mean of a:", np.mean(a))
print("Sum of b:", np.sum(b))

