# -*- coding: utf-8 -*-
"""Pandas Data Manipulation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1649sxqayfpcaXLKgtsXldh3eFtHZJ3pX
"""

import pandas as pd

# Create DataFrame
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, None],
    'Score': [85, 90, None, 95]
}
df = pd.DataFrame(data)

# View first rows
print(df.head())

# Select column
print(df['Age'])

# Filter rows
print(df[df['Score'] > 85])

# Handling missing values
df_cleaned = df.dropna()
print("Cleaned DataFrame:\n", df_cleaned)

# Grouping & aggregation
df['Age'] = df['Age'].fillna(df['Age'].mean())  # fill missing age
grouped = df.groupby('Age')['Score'].mean()
print("Grouped Data:\n", grouped)

