# -*- coding: utf-8 -*-
"""week 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1649sxqayfpcaXLKgtsXldh3eFtHZJ3pX
"""

# Week 2 Hands-On Practice

# Sum of Squares
def sum_of_squares(numbers):
    return sum([x**2 for x in numbers])

print("Sum of squares:", sum_of_squares([1, 2, 3, 4]))

# Filtering Even Numbers
numbers = [1, 2, 3, 4, 5, 6]
even_numbers = list(filter(lambda x: x % 2 == 0, numbers))
print("Even Numbers:", even_numbers)

# Recursion - Factorial
def factorial(n):
    if n == 0:
        return 1
    return n * factorial(n - 1)

print("Factorial of 5:", factorial(5))

