# -*- coding: utf-8 -*-
"""week 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1649sxqayfpcaXLKgtsXldh3eFtHZJ3pX
"""

# Client Project: Data Cleaning Script

def clean_data(data):
    # Remove duplicates
    data = list(set(data))

    # Filter out None, empty, or whitespace-only values
    data = [item for item in data if item not in (None, "", " ")]

    return data

raw_data = ["apple", "banana", "apple", None, " ", "grape", "banana"]
cleaned_data = clean_data(raw_data)

print("Original Data:", raw_data)
print("Cleaned Data:", cleaned_data)

